export const API_ERROR = 'EVENT/API_ERROR_RECEIVED'
export const WEATHER_DATA_RECEIVED = 'EVENT/WEATHER_DATA_RECEIVED'

export const FETCH_METRICS = 'COMMAND/FETCH_METRICS'
export const METRICS_RECEIVED = 'EVENT/METRICS_RECEIVED'

export const FETCH_METRICS_DATA = 'COMMAND/FETCH_METRICS_DATA'
export const METRICS_DATA_RECEIVED = 'EVENT/METRICS_DATA_RECEIVED'

export const FETCH_PAST_METRICS_DATA = 'COMMAND/FETCH_PAST_METRICS_DATA'
export const PAST_METRICS_DATA_RECEIVED = 'EVENT/PAST_METRICS_DATA_RECEIVED'
